version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
       MONGO_HOST: database
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - ./mongo_data:/data/mydb

networks:
  app-network:
    driver: bridge
volumes:
  mongo_data: